version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    command: npm run dev

  calc:
    build:
      context: ./calc
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./calc:/app
      - /app/node_modules
    command: npm run dev

  carte:
    build:
      context: ./carte
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./carte:/app
      - /app/node_modules
    command: npm run dev

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: develop
      MYSQL_DATABASE: password
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
