services:
  api:
    image: node:22-alpine
    working_dir: /workspace
    ports:
      - "8080:8080"
    volumes:
      - ./:/workspace
      - root_node_modules:/workspace/node_modules
    command: sh -c "cd /workspace && npm i && npm run -w apps/api dev"
    depends_on:
      - db

  carte:
    image: node:22-alpine
    working_dir: /workspace
    ports:
      - "8082:8082"
    volumes:
      - ./:/workspace
      - root_node_modules:/workspace/node_modules
    command: sh -c "cd /workspace && npm i && npm run -w apps/carte dev"
    depends_on:
      - db

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: dev
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data:
  root_node_modules: